### ISSUE TITLE
Wireguard container error

### ISSUE THREAD

**Issue by Jihadist** [amnezia-vpn/amnezia-client#57]
I see in wireguard client logs
```
Handshake for peer 1 (*:51820) did not complete after 5 seconds
```
Then I try to attach docker container with wireguard and restart wireguard manually but I cannot
```bash
bash-5.1# wg-quick up /opt/amnezia/wireguard/wg0.conf
Warning: `/opt/amnezia/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
RTNETLINK answers: Not supported
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"
```

Amnezia v 2.0.8

**Comment by pokamest** [comment]
The errors you're seeing indicate that the WireGuard kernel module is not installed or is not supported in your VPS server's virtualization environment.

If you're running a virtual private server (VPS) and your virtualization environment doesn't support the WireGuard kernel module, you may face challenges in setting up a WireGuard VPN. This issue arises because certain virtualization environments don't allow for the full range of kernel module operations that are required for WireGuard to function.

You may need to consider switching to a different VPS provider that supports kernel modules (KVM virtualization).
We are planning to implement the server-side functionality using wireguard-go, which will address this issue.

**Comment by Jihadist** [comment]
@pokamest thanx
