### ISSUE TITLE
One device can use VPN

### ISSUE THREAD

**Issue by davoodice** [amnezia-vpn/amnezia-client#693]
**Describe
When I share my Connection (AWG), and connect my two devices, just one of them can access to internet . They are connected successfully, but the Internet back and forth between devices. (ping pong). Until one of them disconnect by me. 

**To Reproduce
connect two devices to same connection

**Server 
Ubuntu 22.04

**Comment by MagnetizedFreckles** [comment]
AFAIK this problem comes from the WireGuard protocol itself, it has been there since the beginning, and it could be argued that this isn't a bug, just a protocol quirk.
So the intention there is to make users generate different keys for different devices.

**Comment by davoodice** [comment]
Thanks. Is there any way to do that in amnezia config?

**Comment by MagnetizedFreckles** [comment]
I believe, it should be done according to [this guide](https://amnezia.org/en/instructions/10_sharing-connect), but right now I can't correctly install on a new server and reproduce your issue. Probably will try later.  

I suppose you tried to share connection with administrative rights, and it just copied existing key instead of generating a new one (creators of Amnezia probably done like this because some security reasons, but idk).  
But if your issue happens when generating a new user *without* administrative access... Well, that's a serious bug.

**Comment by pokamest** [comment]
@davoodice you need to share config two times for two devices.
WireGuard/AWG don't support multiple simultaneous connections using single config and key.
